version: '3.8'

services:
  express:
    container_name: express-app
    build: ./frontend
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=mongo_db
    depends_on:
      - mariadb
      - mongodb
    networks:
      - app_network

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=mysql_db
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mysql
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks:
      - app_network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=mongo_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: --quiet
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:

